### ISSUE TITLE
USER STORY:<TITLE>

### ISSUE THREAD

**Issue by Stojj2** [Stojj2/My-First-Agile-Project#6]
As a **administrator** I can **invite new users** so that **I have control on the members of the site**

## Acceptance Criteria
  - Inviting via email
  - If a user is already invited i will get a error

## Tasks
- [ ] Develop HTML for administrator page
- [ ] Develop CSS for administrator page
- [ ] Develop Python logic for if a user exists
