### ISSUE TITLE
USER STORY: User newsletter

### ISSUE THREAD

**Issue by Stojj2** [Stojj2/My-First-Agile-Project#7]
As a **user** I can **opt in for a newsletter** so that **I have the latest information from the administrator**

## Acceptance Criteria
  - Newsletter should be short with no pictures, more like a update message
  - Newsletter is sent out via email

## Tasks
- [ ] Develop a standard newsletter template in javascript
- [ ] Develop database for user's opted in for newsletter
- [ ] Develop a newsletter HTML section for administrator 
- [ ] develop CSS for newsletter administrator section
